// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClk1K0nMDON0pvN18NGBr_wWoibhrHD1o',
    appId: '1:736480993816:web:ad02cca02b5e925894996d',
    messagingSenderId: '736480993816',
    projectId: 'food-tutor',
    authDomain: 'food-tutor.firebaseapp.com',
    storageBucket: 'food-tutor.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwJzuIWWZxmjYZfXrLODQ7PjX_goAAhe4',
    appId: '1:736480993816:android:5d6241ed79a133ee94996d',
    messagingSenderId: '736480993816',
    projectId: 'food-tutor',
    storageBucket: 'food-tutor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyBeidflrxRxBzBPfE0nWN24qkAk3kcyY',
    appId: '1:736480993816:ios:40017ba22639f36194996d',
    messagingSenderId: '736480993816',
    projectId: 'food-tutor',
    storageBucket: 'food-tutor.appspot.com',
    iosBundleId: 'com.example.foodTutor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyBeidflrxRxBzBPfE0nWN24qkAk3kcyY',
    appId: '1:736480993816:ios:0b30695f2dd14abf94996d',
    messagingSenderId: '736480993816',
    projectId: 'food-tutor',
    storageBucket: 'food-tutor.appspot.com',
    iosBundleId: 'com.example.foodTutor.RunnerTests',
  );
}
